package com.quantlab.backend.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Response DTO for screening operations.
 * Contains screening signals grouped by strategy code.
 */
public class ScreeningResponse {

    @JsonProperty("screeningDate")
    @NotNull
    private LocalDate screeningDate;

    @JsonProperty("market")
    private String market;

    /**
     * Map of strategy code to list of screening signals generated by that strategy.
     * For example: {"EOD_BREAKOUT": [signal1, signal2], "SMA_CROSSOVER": [signal3]}
     */
    @JsonProperty("signalsByStrategy")
    @NotNull
    private Map<String, List<ScreeningSignal>> signalsByStrategy;

    /**
     * Total count of actionable signals across all strategies.
     */
    @JsonProperty("totalSignals")
    @NotNull
    private Integer totalSignals;

    /**
     * Timestamp when screening was completed.
     */
    @JsonProperty("timestamp")
    @NotNull
    private String timestamp;

    public ScreeningResponse() {
    }

    public ScreeningResponse(LocalDate screeningDate, String market,
                            Map<String, List<ScreeningSignal>> signalsByStrategy,
                            Integer totalSignals, String timestamp) {
        this.screeningDate = screeningDate;
        this.market = market;
        this.signalsByStrategy = signalsByStrategy;
        this.totalSignals = totalSignals;
        this.timestamp = timestamp;
    }

    public LocalDate getScreeningDate() {
        return screeningDate;
    }

    public void setScreeningDate(LocalDate screeningDate) {
        this.screeningDate = screeningDate;
    }

    public String getMarket() {
        return market;
    }

    public void setMarket(String market) {
        this.market = market;
    }

    public Map<String, List<ScreeningSignal>> getSignalsByStrategy() {
        return signalsByStrategy;
    }

    public void setSignalsByStrategy(Map<String, List<ScreeningSignal>> signalsByStrategy) {
        this.signalsByStrategy = signalsByStrategy;
    }

    public Integer getTotalSignals() {
        return totalSignals;
    }

    public void setTotalSignals(Integer totalSignals) {
        this.totalSignals = totalSignals;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ScreeningResponse that = (ScreeningResponse) o;
        return Objects.equals(screeningDate, that.screeningDate) &&
                Objects.equals(market, that.market) &&
                Objects.equals(signalsByStrategy, that.signalsByStrategy) &&
                Objects.equals(totalSignals, that.totalSignals) &&
                Objects.equals(timestamp, that.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(screeningDate, market, signalsByStrategy, totalSignals, timestamp);
    }

    @Override
    public String toString() {
        return "ScreeningResponse{" +
                "screeningDate=" + screeningDate +
                ", market='" + market + '\'' +
                ", signalsByStrategy=" + signalsByStrategy +
                ", totalSignals=" + totalSignals +
                ", timestamp='" + timestamp + '\'' +
                '}';
    }
}
