
import React, { useState, useEffect } from 'react';
import { apiService } from '../services/apiService';
import { Signal } from '../types';

interface SignalsProps {
  runId: number | null;
}

const Signals: React.FC<SignalsProps> = ({ runId }) => {
  const [signals, setSignals] = useState<Signal[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!runId) return;
    const fetchSignals = async () => {
      setLoading(true);
      try {
        const data = await apiService.getSignals(runId);
        setSignals(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchSignals();
  }, [runId]);

  const exportCSV = () => {
    if (signals.length === 0) return;
    const headers = Object.keys(signals[0]).join(',');
    const rows = signals.map(s => Object.values(s).join(',')).join('\n');
    const csvContent = "data:text/csv;charset=utf-8," + headers + "\n" + rows;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `signals_run_${runId}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!runId) return <div className="text-center p-20 text-slate-500">Run a strategy first to see signals.</div>;
  if (loading) return <div className="p-8 text-center text-slate-500">Fetching signals...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">Trade Signals</h2>
          <p className="text-sm text-slate-500">Entry and exit signals generated by the selected model</p>
        </div>
        <button 
          onClick={exportCSV}
          className="bg-slate-800 hover:bg-slate-700 text-slate-300 px-4 py-2 rounded-lg text-sm font-semibold border border-slate-700 transition-colors"
        >
          Export CSV
        </button>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-800/50 text-[10px] uppercase tracking-widest text-slate-500 font-bold border-b border-slate-800">
              <th className="px-6 py-4">Symbol</th>
              <th className="px-6 py-4">Date</th>
              <th className="px-6 py-4">Side</th>
              <th className="px-6 py-4">Buy Price</th>
              <th className="px-6 py-4">Stop Loss</th>
              <th className="px-6 py-4">Target</th>
              <th className="px-6 py-4">Qty</th>
              <th className="px-6 py-4">Strategy</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800">
            {signals.map((signal, idx) => (
              <tr key={idx} className="hover:bg-slate-800/30 transition-colors text-sm">
                <td className="px-6 py-4 font-bold text-slate-200 mono">{signal.symbol}</td>
                <td className="px-6 py-4 text-slate-400 mono">{signal.signalDate}</td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${signal.side === 'BUY' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-rose-500/10 text-rose-400'}`}>
                    {signal.side}
                  </span>
                </td>
                <td className="px-6 py-4 text-slate-300 mono">${signal.entryPrice.toFixed(2)}</td>
                <td className="px-6 py-4 text-rose-400/80 mono">${signal.stopLoss.toFixed(2)}</td>
                <td className="px-6 py-4 text-emerald-400/80 mono">${signal.targetPrice.toFixed(2)}</td>
                <td className="px-6 py-4 text-slate-300 mono">{signal.quantity}</td>
                <td className="px-6 py-4 text-slate-500 text-xs">{signal.strategy}</td>
              </tr>
            ))}
            {signals.length === 0 && (
              <tr>
                <td colSpan={8} className="px-6 py-12 text-center text-slate-500 italic">No signals generated for this run.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Signals;
