
import React, { useState, useEffect } from 'react';
import { apiService } from '../services/apiService';
import { Signal } from '../types';

const sortTooltip = 'Click to sort';

interface SignalsProps {
  runId: number | null;
}

type SortField = keyof Signal;
type SortDirection = 'asc' | 'desc';

const Signals: React.FC<SignalsProps> = ({ runId }) => {
  const [signals, setSignals] = useState<Signal[]>([]);
  const [loading, setLoading] = useState(false);
  const [sortField, setSortField] = useState<SortField>('signalDate');
  const [sortDirection, setSortDirection] = useState<SortDirection>('desc');

  useEffect(() => {
    if (!runId) return;
    const fetchSignals = async () => {
      setLoading(true);
      try {
        const data = await apiService.getSignals(runId);
        setSignals(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchSignals();
  }, [runId]);

  const handleSort = (field: SortField) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('desc');
    }
  };

  const sortedSignals = [...signals].sort((a, b) => {
    const aValue = a[sortField];
    const bValue = b[sortField];

    if (aValue === null || aValue === undefined) return 1;
    if (bValue === null || bValue === undefined) return -1;

    if (typeof aValue === 'string' && typeof bValue === 'string') {
      return sortDirection === 'asc'
        ? aValue.localeCompare(bValue)
        : bValue.localeCompare(aValue);
    }

    if (typeof aValue === 'number' && typeof bValue === 'number') {
      return sortDirection === 'asc'
        ? aValue - bValue
        : bValue - aValue;
    }

    return 0;
  });

  const getSortIndicator = (field: SortField) => {
    if (sortField !== field) return null;
    return (
      <span className="text-xs">
        {sortDirection === 'asc' ? '▲' : '▼'}
      </span>
    );
  };

  const exportCSV = () => {
    if (signals.length === 0) return;
    const headers = Object.keys(signals[0]).join(',');
    const rows = signals.map(s => Object.values(s).join(',')).join('\n');
    const csvContent = "data:text/csv;charset=utf-8," + headers + "\n" + rows;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `signals_run_${runId}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!runId) return <div className="text-center p-20 text-slate-500">Run a strategy first to see signals.</div>;
  if (loading) return <div className="p-8 text-center text-slate-500">Fetching signals...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">Trade Signals</h2>
          <p className="text-sm text-slate-500">Entry and exit signals generated by the selected model</p>
        </div>
        <button
          onClick={exportCSV}
          className="bg-slate-800 hover:bg-slate-700 text-slate-300 px-4 py-2 rounded-lg text-sm font-semibold border border-slate-700 transition-colors"
        >
          Export CSV
        </button>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden max-h-[calc(100vh-300px)] overflow-y-auto">
        <table className="w-full text-left border-collapse sticky top-0">
          <thead>
            <tr className="bg-slate-800/50 text-[10px] uppercase tracking-widest text-slate-500 font-bold border-b border-slate-800">
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'symbol' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('symbol')}
                title={sortTooltip}
              >
                Symbol {getSortIndicator('symbol')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'signalDate' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('signalDate')}
              >
                Date {getSortIndicator('signalDate')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'side' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('side')}
              >
                Side {getSortIndicator('side')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'entryPrice' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('entryPrice')}
              >
                Buy Price {getSortIndicator('entryPrice')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'stopLoss' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('stopLoss')}
              >
                Stop Loss {getSortIndicator('stopLoss')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'targetPrice' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('targetPrice')}
              >
                Target {getSortIndicator('targetPrice')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'quantity' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('quantity')}
              >
                Qty {getSortIndicator('quantity')}
              </th>
              <th
                className={`px-6 py-4 cursor-pointer transition-colors flex items-center gap-1 ${
                  sortField === 'strategy' ? 'text-slate-300' : 'hover:text-slate-300'
                }`}
                onClick={() => handleSort('strategy')}
              >
                Strategy {getSortIndicator('strategy')}
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800">
            {sortedSignals.map((signal, idx) => (
              <tr key={idx} className="hover:bg-slate-800/30 transition-colors text-sm">
                <td className="px-6 py-4 font-bold text-slate-200 mono">{signal.symbol}</td>
                <td className="px-6 py-4 text-slate-400 mono">{signal.signalDate}</td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${signal.side === 'BUY' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-rose-500/10 text-rose-400'}`}>
                    {signal.side}
                  </span>
                </td>
                <td className="px-6 py-4 text-slate-300 mono">{signal.entryPrice.toFixed(2)}</td>
                <td className="px-6 py-4 text-rose-400/80 mono">{signal.stopLoss !== null ? signal.stopLoss.toFixed(2) : 'N/A'}</td>
                <td className="px-6 py-4 text-emerald-400/80 mono">{signal.targetPrice !== null ? signal.targetPrice.toFixed(2) : 'N/A'}</td>
                <td className="px-6 py-4 text-slate-300 mono">{signal.quantity}</td>
                <td className="px-6 py-4 text-slate-500 text-xs">{signal.strategy}</td>
              </tr>
            ))}
            {signals.length === 0 && (
              <tr>
                <td colSpan={8} className="px-6 py-12 text-center text-slate-500 italic">No signals generated for this run.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Signals;
