package com.quantlab.backend.controller;

import com.quantlab.backend.dto.AnalyticsResponse;
import com.quantlab.backend.dto.EquityCurvePoint;
import com.quantlab.backend.dto.PaperTradeResponse;
import com.quantlab.backend.dto.TradeSignalResponse;
import com.quantlab.backend.service.AnalyticsService;
import com.quantlab.backend.service.StrategyRunService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * REST Controller for Strategy Run management.
 * Handles API endpoints for retrieving strategy run results including signals,
 * paper trades, analytics, and equity curve data.
 */
@RestController
@RequestMapping("/api/v1/strategy-runs")
public class StrategyRunController {

    private final StrategyRunService strategyRunService;
    private final AnalyticsService analyticsService;

    /**
     * Constructor-based dependency injection.
     *
     * @param strategyRunService the strategy run service
     * @param analyticsService the analytics service
     */
    public StrategyRunController(StrategyRunService strategyRunService, AnalyticsService analyticsService) {
        this.strategyRunService = strategyRunService;
        this.analyticsService = analyticsService;
    }

    /**
     * Get trade signals for a specific strategy run.
     *
     * @param id the strategy run ID
     * @return list of trade signals generated by the strategy
     */
    @GetMapping("/{id}/signals")
    public ResponseEntity<List<TradeSignalResponse>> getTradeSignals(@PathVariable("id") Long id) {
        List<TradeSignalResponse> signals = strategyRunService.getTradeSignals(id);
        return ResponseEntity.ok(signals);
    }

    /**
     * Get paper trades for a specific strategy run.
     *
     * @param id the strategy run ID
     * @return list of completed paper trades
     */
    @GetMapping("/{id}/paper-trades")
    public ResponseEntity<List<PaperTradeResponse>> getPaperTrades(@PathVariable("id") Long id) {
        List<PaperTradeResponse> paperTrades = strategyRunService.getPaperTrades(id);
        return ResponseEntity.ok(paperTrades);
    }

    /**
     * Get analytics summary for a specific strategy run.
     *
     * @param id the strategy run ID
     * @return analytics summary including total trades, win rate, total PnL, and max drawdown
     */
    @GetMapping("/{id}/analytics")
    public ResponseEntity<AnalyticsResponse> getAnalytics(@PathVariable("id") Long id) {
        AnalyticsResponse analytics = analyticsService.getAnalytics(id);
        return ResponseEntity.ok(analytics);
    }

    /**
     * Get equity curve data for a specific strategy run.
     *
     * @param id the strategy run ID
     * @return list of equity curve points with date and equity value
     */
    @GetMapping("/{id}/equity-curve")
    public ResponseEntity<List<EquityCurvePoint>> getEquityCurve(@PathVariable("id") Long id) {
        List<EquityCurvePoint> equityCurve = analyticsService.getEquityCurve(id);
        return ResponseEntity.ok(equityCurve);
    }
}
